ToDoList/Controllers/RegistrationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ToDoList.Database;
using ToDoList.Database.Entities;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class RegistrationController : Controller
    {
        readonly DatabaseContext db;

        public RegistrationController()
        {
            db = new DatabaseContext();
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registration(RegistrationModel registrationModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User user = db.Users.FirstOrDefault(e => e.Email == registrationModel.Email);
                    if (user == null)
                    {
                        PasswordHasher passwordHash = new PasswordHasher();
                        user = new User
                        {
                            Email = registrationModel.Email,
                            Password = passwordHash.HashPassword(registrationModel.Password),
                            Login = registrationModel.Login
                        };
                        db.Users.Add(user);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Task");
                    }
                    else
                    {
                        ViewBag.Message = "The user with such Email exist";
                        return View(registrationModel);
                    }
                }
                return View(registrationModel);
            }
            catch
            {
                return RedirectToAction("Error404", "Home");
            }
        }
    }
}

ToDoList/Controllers/SignInController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ToDoList.Database;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class SignInController : Controller
    {
        private readonly DatabaseContext db;

        public SignInController()
        {
            db = new DatabaseContext();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(SignInModel signInModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = db.Users.FirstOrDefault(e => e.Email == signInModel.Email);
                    if (user != null)
                    {
                        PasswordHasher passwordHasher = new PasswordHasher();
                        var result = passwordHasher.VerifyHashedPassword(user.Password, signInModel.Password);
                        if (result == PasswordVerificationResult.Success)
                        {
                            var claims = new List<Claim>
                            {
                                new Claim(ClaimTypes.Name, user.Login), // User Name
                                new Claim(ClaimTypes.PrimarySid, user.Id.ToString()) // User ID
                            };
                            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var principal = new ClaimsPrincipal(identity);
                            var props = new AuthenticationProperties();
                            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props).Wait();
                            return RedirectToAction("Index", "Task");
                        }
                    }
                    ViewBag.Message = "We cannot find such account. Please check Email and password";
                    return View(signInModel);
                }
                return View(signInModel);
            }
            catch
            {
                return RedirectToAction("Error404", "Home");
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-0">
                        @if (ViewBag.Login != null)
                        {
                            <li class="nav-item">
                                <a class="navbar-brand">Hello @ViewBag.Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="SignIn" asp-action="LogOut">LogOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="SignIn" asp-action="Login">Sign-In</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="Registration" asp-action="Registration">Registration</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoList
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>